// src/js/components/shepherd-header.jsx
import preact from 'preact';

const { Component } = preact;

export default class ShepherdHeader extends Component {
  constructor(props) {
    super(props);

    this.step = props.step;

    this.cancelStep = this.cancelStep.bind(this);
  }

  render(props) {
    const { labelId, options, styles } = props;
    const { showCancelLink, title } = options;
    return <header className={styles.header.trim()}>
      {this.constructor._addTitle(title, labelId, styles)}
      {this._addCancelLink(showCancelLink, styles)}
    </header>;
  }

  /**
   * Add a click listener to the cancel link that cancels the tour
   */
  cancelStep(e) {
    e.preventDefault();
    this.step.cancel();
  }

  static _addTitle(title, labelId, styles) {
    if (title) {
      return <h3
        id={labelId}
        className={styles.title.trim()}
      >
        {title}
      </h3>;
    }

    return null;
  }

  _addCancelLink(showCancelLink, styles) {
    if (showCancelLink) {
      return <a
        href=''
        className={styles['cancel-link'].trim()}
        onClick={this.cancelStep}
      />;
    }

    return null;
  }
}

// src/js/components/shepherd-content/shepherd-header/index.svelte
<script>
  export let labelId, step, styles;
  const { cancelIcon, title } = step.options;

  /**
   * Add a click listener to the cancel link that cancels the tour
   */
  const handleCancelClick = (e) => {
    e.preventDefault();
    step.cancel();
  };
</script>

<header class="{styles.header.trim()}">
    {#if title}
      <h3
        id="{labelId}"
        class="{styles.title.trim()}"
      >
          {title}
      </h3>
    {/if}

    {#if cancelIcon && cancelIcon.enabled}
      <button
        aria-label="{cancelIcon.label ? cancelIcon.label : 'Close Tour'}"
        class="{styles['cancel-icon'].trim()}"
        on:click={handleCancelClick}
        type="button"
      >
        <span aria-hidden="true">&times;</span>
      </button>
    {/if}
</header>
