// src/js/components/shepherd-footer.jsx
import preact from 'preact';
import ShepherdButton from './shepherd-button.jsx';

const { Component } = preact;

export default class ShepherdFooter extends Component {
  render(props) {
    const { classPrefix, step, styles } = props;
    const { buttons } = step.options;

    return <footer className={styles.footer.trim()}>
      {this._addButtons(buttons, classPrefix, styles)}
    </footer>;
  }

  _addButtons(buttons, classPrefix, styles) {
    if (buttons) {
      return buttons.map((config) => {
        return <ShepherdButton classPrefix={classPrefix} config={config} styles={styles}/>;
      });
    }

    return null;
  }
}

// src/js/components/shepherd-content/shepherd-footer/index.svelte
<script>
  import ShepherdButton from './shepherd-button';

  export let classPrefix, step, styles;
  const { buttons } = step.options;
</script>

<footer class="{styles.footer.trim()}">
    {#if buttons}
        {#each buttons as config}
          <ShepherdButton
            {classPrefix}
            {config}
            {step}
            {styles}
          />
        {/each}
    {/if}
</footer>
