// src/js/components/shepherd-content/shepherd-footer/shepherd-button/index.jsx
import preact from 'preact';

const { Component } = preact;

export default class ShepherdButton extends Component {
  render(props) {
    const { classPrefix, config, step, styles } = props;
    const { action, classes, secondary, text } = config;

    return <button
      className={(classes || '') + styles.button + (secondary ? ` ${classPrefix}shepherd-button-secondary` : '')}
      onClick={action ? action.bind(step.tour) : null}
      tabindex='0'>
      {text}
    </button>;
  }
}

// src/js/components/shepherd-content/shepherd-footer/shepherd-button/index.svelte
<script>
  export let classPrefix, config, step, styles;
  const { action, classes, secondary, text } = config;
</script>


<button
  class="{(classes || '') + styles.button + (secondary ? ` ${classPrefix}shepherd-button-secondary` : '')}"
  on:click={action ? action.bind(step.tour) : null}
  tabindex='0'
>
    {text}
</button>
