// shepherd.js/src/components/shepherd-header.svelte
<script>
  import ShepherdCancelIcon from './shepherd-cancel-icon.svelte';
  import ShepherdTitle from './shepherd-title.svelte';

  const { labelId, step } = $props();

  let title = $derived(step.options.title);
  let cancelIcon = $derived(step.options.cancelIcon);
</script>

<header class="shepherd-header">
  {#if title}
    <ShepherdTitle {labelId} {title} />
  {/if}

  {#if cancelIcon && cancelIcon.enabled}
    <ShepherdCancelIcon {cancelIcon} {step} />
  {/if}
</header>

// shepherd.js/src/components/shepherd-header.tsx
import { h } from 'preact';

import ShepherdCancelIcon from './shepherd-cancel-icon';
import ShepherdTitle from './shepherd-title';
import type { Step } from '../step';

export interface ShepherdHeaderProps {
  labelId: string;
  step: Step;
}

export default function ShepherdHeader({ labelId, step }: ShepherdHeaderProps) {
  return (
    <header className="shepherd-header">
      {step.options.title && <ShepherdTitle labelId={labelId} title={step.options.title} />}
      
      {step.options.cancelIcon && step.options.cancelIcon.enabled && (
        <ShepherdCancelIcon cancelIcon={step.options.cancelIcon} step={step} />
      )}
    </header>
  );
}
