// src/components/shepherd-button.svelte
<script>
  import { isFunction } from '../utils/type-check';

  export let config, step;
  let action, classes, disabled, label, secondary, text;

  $: {
    action = config.action ? config.action.bind(step.tour) : null;
    classes = config.classes;
    disabled = config.disabled ? getConfigOption(config.disabled) : false;
    label = config.label ? getConfigOption(config.label) : null;
    secondary = config.secondary;
    text = config.text ? getConfigOption(config.text) : null;
  }

  function getConfigOption(option) {
    if (isFunction(option)) {
      return option = option.call(step);
    }
    return option;
  }

</script>

<style global>
  .shepherd-button {
    background: rgb(50, 136, 230);
    border: 0;
    border-radius: 3px;
    color: rgba(255, 255, 255, 0.75);
    cursor: pointer;
    margin-right: 0.5rem;
    padding: 0.5rem 1.5rem;
    transition: all 0.5s ease;
  }

  .shepherd-button:not(:disabled):hover {
    background: rgb(25, 111, 204);
    color: rgba(255, 255, 255, 0.75);
  }

  .shepherd-button.shepherd-button-secondary {
    background: rgb(241, 242, 243);
    color: rgba(0, 0, 0, 0.75);
  }

  .shepherd-button.shepherd-button-secondary:not(:disabled):hover {
    background: rgb(214, 217, 219);
    color: rgba(0, 0, 0, 0.75);
  }

  .shepherd-button:disabled {
    cursor: not-allowed;
  }
</style>

<button
  aria-label="{label ? label : null}"
  class="{`${(classes || '')} shepherd-button ${(secondary ? 'shepherd-button-secondary' : '')}`}"
  disabled={disabled}
  on:click={action}
  tabindex="0"
>
    {@html text}
</button>

// shepherd.js/src/components/shepherd-button.tsx
import { h } from 'preact';

import { isFunction } from '../utils/type-check';
import type { Step, StepOptionsButton } from '../step';

export interface ShepherdButtonProps {
  config: StepOptionsButton;
  step: Step;
}

export default function ShepherdButton({ config, step }: ShepherdButtonProps) {
  const getConfigOption = (option: any) => {
    if (isFunction(option)) {
      return option.call(step);
    }
    return option;
  };

  const action = config.action ? config.action.bind(step.tour) : null;
  const disabled = config.disabled ? getConfigOption(config.disabled) : false;
  const label = config.label ? getConfigOption(config.label) : null;
  const text = config.text ? getConfigOption(config.text) : null;

  return (
    <button
      aria-label={label || undefined}
      className={`${config.classes || ''} shepherd-button ${
        config.secondary ? 'shepherd-button-secondary' : ''
      }`}
      disabled={disabled}
      onClick={() => action?.()}
      tabIndex={0}
      type="button"
      dangerouslySetInnerHTML={{ __html: text }}
    />
  );
}
