// shepherd.js/src/components/shepherd-title.tsx
import { createEffect, onMount } from 'solid-js';
import { isFunction } from '../utils/type-check';
import type { StringOrStringFunction } from '../step';

export interface ShepherdTitleProps {
  labelId: string;
  title: StringOrStringFunction;
}

export default function ShepherdTitle(props: ShepherdTitleProps) {
  let element: HTMLHeadingElement | undefined;

  createEffect(() => {
    if (element) {
      let title = props.title;
      if (isFunction(title)) {
        title = title();
      }
      element.innerHTML = title;
    }
  });

  return <h3 ref={element} id={props.labelId} class="shepherd-title" />;
}

// shepherd.js/src/components/shepherd-title.svelte
<script>
  import { isFunction } from '../utils/type-check.ts';

  let { labelId, element, title } = $props();

  $effect(() => {
    let currentTitle = title;
    if (isFunction(currentTitle)) {
      currentTitle = currentTitle();
    }
    element.innerHTML = currentTitle;
  });
</script>

<!-- svelte-ignore a11y_missing_content -->
<h3 bind:this={element} id={labelId} class="shepherd-title"></h3>
