// shepherd.js/src/components/shepherd-footer.svelte
<script>
  import ShepherdButton from './shepherd-button.svelte';

  const { step } = $props();

  let buttons = $derived(step.options.buttons ?? []);
</script>

<footer class="shepherd-footer">
  {#if buttons}
    {#each buttons as config}
      <ShepherdButton {config} {step} />
    {/each}
  {/if}
</footer>

// shepherd.js/src/components/shepherd-footer.tsx
import { For, Show } from 'solid-js';
import ShepherdButton from './shepherd-button';
import type { Step } from '../step';

export interface ShepherdFooterProps {
  step: Step;
}

export default function ShepherdFooter(props: ShepherdFooterProps) {
  return (
    <footer class="shepherd-footer">
      <Show when={props.step.options.buttons}>
        <For each={props.step.options.buttons}>
          {(config) => <ShepherdButton config={config} step={props.step} />}
        </For>
      </Show>
    </footer>
  );
}
