// src/src/js/components/shepherd-text.svelte
<script>
  import { afterUpdate } from 'svelte';
  import { isHTMLElement, isFunction } from '../utils/type-check';

  export let descriptionId, element, step;

  afterUpdate(() => {
    let { text } = step.options;

    if (isFunction(text)) {
      text = text.call(step);
    }

    if (isHTMLElement(text)) {
      element.appendChild(text);
    } else {
      element.innerHTML = text;
    }
  });
</script>

<style global>
  .shepherd-text {
    color: rgba(0, 0, 0, 0.75);
    font-size: 1rem;
    line-height: 1.3em;
    padding: 0.75em;
  }

  .shepherd-text p {
    margin-top: 0;
  }

  .shepherd-text p:last-child {
    margin-bottom: 0;
  }
</style>

<div
  bind:this={element}
  class="shepherd-text"
  id="{descriptionId}"
>
</div>

// shepherd.js/src/components/shepherd-text.tsx
import { createEffect } from 'solid-js';
import { isHTMLElement, isFunction } from '../utils/type-check';
import type { Step } from '../step';

export interface ShepherdTextProps {
  descriptionId: string;
  step: Step;
}

export default function ShepherdText(props: ShepherdTextProps) {
  let element: HTMLDivElement | undefined;

  createEffect(() => {
    if (element) {
      let text = props.step.options.text;

      if (isFunction(text)) {
        text = text.call(props.step);
      }

      if (isHTMLElement(text)) {
        element.innerHTML = '';
        element.appendChild(text as HTMLElement);
      } else {
        element.innerHTML = text as string;
      }
    }
  });

  return <div ref={element} class="shepherd-text" id={props.descriptionId} />;
}
