// shepherd.js/src/components/shepherd-content.svelte
<script>
import ShepherdFooter from './shepherd-footer.svelte';
import ShepherdHeader from './shepherd-header.svelte'; 
import ShepherdText from './shepherd-text.svelte';
import { isUndefined } from '../utils/type-check.ts';

const { descriptionId, labelId, step } = $props();

<div class="shepherd-content">
  {#if !isUndefined(step.options.title) || (step.options.cancelIcon && step.options.cancelIcon.enabled)}
    <ShepherdHeader {labelId} {step} />
  {/if}

  {#if !isUndefined(step.options.text)}
    <ShepherdText {descriptionId} {step} />
  {/if}

  {#if Array.isArray(step.options.buttons) && step.options.buttons.length}
    <ShepherdFooter {step} />
  {/if}
</div>

// shepherd.js/src/components/shepherd-content.tsx
import { Show } from 'solid-js';
import ShepherdFooter from './shepherd-footer';
import ShepherdHeader from './shepherd-header';
import ShepherdText from './shepherd-text';
import { isUndefined } from '../utils/type-check';
import type { Step } from '../step';

export interface ShepherdContentProps {
  descriptionId: string;
  labelId: string;
  step: Step;
}

export default function ShepherdContent(props: ShepherdContentProps) {
  return (
    <div class="shepherd-content">
      <Show
        when={
          !isUndefined(props.step.options.title) ||
          (props.step.options.cancelIcon &&
            props.step.options.cancelIcon.enabled)
        }
      >
        <ShepherdHeader labelId={props.labelId} step={props.step} />
      </Show>

      <Show when={!isUndefined(props.step.options.text)}>
        <ShepherdText descriptionId={props.descriptionId} step={props.step} />
      </Show>

      <Show
        when={
          Array.isArray(props.step.options.buttons) &&
          props.step.options.buttons.length
        }
      >
        <ShepherdFooter step={props.step} />
      </Show>
    </div>
  );
}
