// shepherd.js/src/components/shepherd-title.tsx
import { createEffect, onMount } from 'solid-js';
import { isFunction } from '../utils/type-check';
import type { StringOrStringFunction } from '../step';

export interface ShepherdTitleProps {
  labelId: string;
  title: StringOrStringFunction;
}

export default function ShepherdTitle(props: ShepherdTitleProps) {
  let element: HTMLHeadingElement | undefined;

  createEffect(() => {
    if (element) {
      let title = props.title;
      if (isFunction(title)) {
        title = title();
      }
      element.innerHTML = title;
    }
  });

  return <h3 ref={element} id={props.labelId} class="shepherd-title" />;
}

// src/js/components/shepherd-title.svelte
<script>
  import { afterUpdate } from 'svelte';
  import { isFunction } from '../utils/type-check';
  
  export let labelId, element, step;
  
  afterUpdate(() => {
    let { title } = step.options;
    
    if (isFunction(title)) {
      title = title();
    }
    
    element.innerHTML = title;
  });
</script>

<style global>
  .shepherd-title {
    color: rgba(0, 0, 0, 0.75);
    display: flex;
    font-size: 1rem;
    font-weight: normal;
    flex: 1 0 auto;
    margin: 0;
    padding: 0;
  }
</style>

<h3
  bind:this={element}
  id="{labelId}"
  class="shepherd-title"
>
</h3>
