// shepherd.js/src/components/shepherd-header.tsx
import { h } from 'preact';

import ShepherdCancelIcon from './shepherd-cancel-icon';
import ShepherdTitle from './shepherd-title';
import type { Step } from '../step';

export interface ShepherdHeaderProps {
  labelId: string;
  step: Step;
}

export default function ShepherdHeader({ labelId, step }: ShepherdHeaderProps) {
  return (
    <header className="shepherd-header">
      {step.options.title && <ShepherdTitle labelId={labelId} title={step.options.title} />}
      
      {step.options.cancelIcon && step.options.cancelIcon.enabled && (
        <ShepherdCancelIcon cancelIcon={step.options.cancelIcon} step={step} />
      )}
    </header>
  );
}

// src/js/components/shepherd-header.svelte
<script>
  import ShepherdCancelIcon from './shepherd-cancel-icon.svelte';
  import ShepherdTitle from './shepherd-title.svelte';

  export let labelId, step;
  const { cancelIcon, title } = step.options;
</script>

<style global>
  .shepherd-header {
    align-items: center;
    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
    display: flex;
    justify-content: flex-end;
    line-height: 2em;
    padding: 0.75rem 0.75rem 0;
  }

  .shepherd-has-title .shepherd-content .shepherd-header {
    background: #e6e6e6;
    padding: 1em;
  }
</style>

<header class="shepherd-header">
    {#if title}
      <ShepherdTitle
        {labelId}
        {title}
      />
    {/if}

    {#if cancelIcon && cancelIcon.enabled}
      <ShepherdCancelIcon
        {cancelIcon}
        {step}
      />
    {/if}
</header>
