// src/js/components/shepherd-content/shepherd-text/index.svelte
<script>
  import { onMount } from 'svelte';
  import { isElement, isFunction } from '../../../utils/type-check';

  export let descriptionId, step, styles;
  let base;

  onMount(() => {
    let { text } = step.options;

    if (isFunction(text)) {
      text = text.call(step);
    }

    if (isElement(text)) {
      base.appendChild(text);
    } else {
      base.innerHTML = text;
    }
  });
</script>

<div
  bind:this={base}
  class="{styles.text.trim()}"
  id="{descriptionId}"
>
</div>

// src/js/components/shepherd-text.jsx
import preact from 'preact';
import { isFunction } from '../utils/type-check';

const { Component } = preact;

export default class ShepherdText extends Component {
  render(props) {
    const { descriptionId, step, styles } = props;
    let { text } = step.options;

    if (isFunction(text)) {
      text = text.call(step);
    }

    return <div
      className={styles.text.trim()}
      dangerouslySetInnerHTML={{ __html: text }}
      id={descriptionId}
    />;
  }
}
